run:
  go: '1.18'
linters:
  enable-all: true
  disable:
  - funlen
  - varnamelen
  - nlreturn
  - godot
  - tagliatelle
  - paralleltest
  - gomnd
  - exhaustivestruct
  - golint
  - gosec
  - wsl
  - revive
  - lll
  - maligned
  - gofumpt
  - scopelint
  - interfacer
  - goimports
  - gci