run:
  go: '1.18'
linters:
  enable-all: true
  disable:
    # deprecatd
    - golint
    - scopelint
    - exhaustivestruct
    - interfacer
    - varcheck
    - deadcode
    - structcheck
    - ifshort
    - maligned
    - nosnakecase
    # useless
    - testableexamples
    - tagliatelle
    - varnamelen
    - usestdlibvars
    - gofumpt
    - funlen
    - lll
    - revive
    - stylecheck
    - exhaustruct
    - gomnd
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: "github.com/go-logr/logr"
            desc: "logging is standardised via logrus"
